### ISSUE TITLE
Improve ignore property

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#32]
I think the `ignore` property can be improved in two ways:

* It should be named `ignores` because it denotes a collection rather than a scalar value
* All entries should be relative because they always depend on `target`. Thus every entry duplicates this information and may lead to errors. Absolute entries shall be rejected.

**Comment by johnmehr** [comment]
I just pushed out the update for this issue (thank you!).  Relative paths are definitely the way to go but I think giving people the option for absolute paths should remain for backwards compatibility.  There was an issue with ignoring files/directories back in the early svnup days and there were some very unhappy people when svnup deleted their distfiles and custom kernel config files and with gitup in the ports tree, I'd really hate for that to happen again.

**Comment by michael-o** [comment]
It looks very nice now! Thanks for the quick turnaround!

**Comment by michael-o** [comment]
The fix is incomplete. Look here: https://github.com/johnmehr/gitup/commit/498ceae5cba1f1207bbdab43d30571beff95e370#diff-d9f0a67b2ce70fb637450347c5cd6d47e136d637ce5060728cfd40f69498aaaeR2029-R2031

You missed to say `"ignores"` for the ucl key as well as to rename the iterator to `it_ignores`. Can you confirm this?

**Comment by johnmehr** [comment]
I just updated the iterator (thank you!) but changing the ucl key to "ignores" would cause problems for anyone that is using the old "ignore" key in their gitup.conf.

**Comment by michael-o** [comment]
> 
> 
> I just updated the iterator (thank you!) but changing the ucl key to "ignores" would cause problems for anyone that is using the old "ignore" key in their gitup.conf.

While that is correct, but:
* This is pre 1.0 you are free to break any contract
* The supplied sample gitup.conf isn't readable already because it correctly contains `"ignores"`:
https://github.com/johnmehr/gitup/blob/3a0ff6c3a14db28fa6e6b2b4c76d976da05dffd1/gitup.conf#L17-L20

**Comment by johnmehr** [comment]
True, but since changes here can result in unintentional file deletion, I think it's best to be extra careful and extra cautious.  The strstr(key, "ignore") should return a non-null for both "ignore" and "ignores" but your fix makes it more explicit and I just committed it.  Thank you!

**Comment by michael-o** [comment]
Agreed. I completely missed that you used `strstr`, but right for the sake of completion your change makes sense.
